FROM __VCENTER_NANNY_BASE_IMAGE__

USER root

ADD scripts scripts

RUN /var/lib/kolla/venv/bin/pip install click==6.7 python-openstackclient==3.12.0
#RUN /var/lib/kolla/venv/bin/pip install click==6.7 python-openstackclient==3.12.0 pyvmomi==6.5.0.2017.5.post1
