#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

FROM __NEUTRON_NANNY_BASE_IMAGE__

USER root

ADD scripts/neutron-* /scripts/

# RUN /var/lib/kolla/venv/bin/pip install click==6.7 python-openstackclient==3.12.0 openstacksdk==0.19.0 prometheus-client==0.1.1 os-client-config==1.30.0 requestsexceptions==1.1.3
#
# # looks like uninstall of dogpile.core is required to avoid a conflict at runtime
# RUN /var/lib/kolla/venv/bin/pip uninstall -y dogpile.core
