apiVersion: v1
kind: Pod
metadata:
  labels:
    name: manila-nanny
  name: manila-nanny-debug
spec:
  containers:
  - name: nanny
    image: keppel.eu-de-1.cloud.sap/ccloud/manila-nanny:latest
    imagePullPolicy: IfNotPresent
    command: [ "python" ]
    args:
      - "/scripts/manila-missing-snapshot.py"
      - "--config"
      - "/manila-etc/manila.conf"
      - "--netapp-filers"
      - "/manila-etc/netapp-filers.yaml"
      - "--interval"
      - "100"
      - "--prom-port"
      - "9505"
    ports:
      - containerPort: 9505
    env:
    - name: DEPENDENCY_SERVICE
      value: manila-mariadb,manila-api
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: MANILA_NANNY_NETAPP_API_USERNAME
      valueFrom:
        secretKeyRef:
          key: manila_netapp_api_username
          name: manila-nanny-secret
    - name: MANILA_NANNY_NETAPP_API_PASSWORD
      valueFrom:
        secretKeyRef:
          key: manila_netapp_api_password
          name: manila-nanny-secret
    volumeMounts:
    - name: manila-etc
      mountPath: /manila-etc/manila.conf
      subPath: manila.conf
    - name: manila-netapp-filers
      mountPath: /manila-etc/netapp-filers.yaml
      subPath: netapp-filers.yaml
    tty: true
    stdin: true
  volumes:
  - name: manila-etc
    configMap:
      defaultMode: 420
      name: manila-etc
  - name: manila-netapp-filers
    configMap:
      defaultMode: 420
      name: manila-netapp-filers-debug
